apiVersion: v1
kind: Namespace
metadata:
  name: dev1
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-cpu-mem-limit-range
  namespace: dev1
spec:
  limits:
    - default:
        cpu: "500m" # If not specified default limit is 1 vCPU per container
        memory: "512Mi" # If not speficied the container's memory limit is set ot 512Mi
      defaultRequest:
        cpu: "300m" # If not specified default it will take from whatever specified in limits.default.cpu
        memory: "256Mi"  # If not specified default it will take from whatever specified in limits.default.memory
      type: Container