apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-perminum-retain-sc

provisioner: kubernetes.io/azure-disk   # what needs to be created
reclaimPolicy: Retain                   # what will happen to PV if PVC gets deleted
volumeBindingMode: WaitForFirstConsumer # define when actual PV should be created
allowVolumeExpansion: true              # allowing resizing the disk after creation

parameters:
  storageaccounttype: Premium_LRS 
  kind: managed
