apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:    # Creating the Pods in Recreate manner
    name: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          env:      # Setting up initial variables required for database
            - name: MYSQL_ROOT_PASSWORD
              value: dbpassword11
          ports:    # SQL port exposed on container 
            - containerPort: 3306
              name: mysql

          # volumeMounts is container level property
          # mount the volumes in perticular path
          volumeMounts:
            - name: mysql-persistant-storage
              mountPath: /var/lib/mysql
            - name: usermanagement-dbcreation-script
              mountPath: /docker-entrypoint-initdb.d
      # volumes is Pod level property
      # Define the volume which needs to be created along with this deployment
      volumes:
        - name: mysql-persistant-storage
          persistentVolumeClaim:
            claimName: azure-managed-disk-pvc
        - name: usermanagement-dbcreation-script
          configMap:
            name: usermanagement-dbcreation-script
